In [40]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
%matplotlib inline

Dataset - https://www.kaggle.com/datasets/ashwiniyer176/toxic-tweets-dataset?resource=download

In [41]:
data = pd.read_csv("FinalBalancedDataset.csv")

In [42]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56745 entries, 0 to 56744
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  56745 non-null  int64 
 1   Toxicity    56745 non-null  int64 
 2   tweet       56745 non-null  object
dtypes: int64(2), object(1)
memory usage: 1.3+ MB


In [43]:
data.head(5)

Unnamed: 0  Toxicity                                              tweet
0           0         0   @user when a father is dysfunctional and is s...
1           1         0  @user @user thanks for #lyft credit i can't us...
2           2         0                                bihday your majesty
3           3         0  #model   i love u take with u all the time in ...
4           4         0             factsguide: society now    #motivation

In [44]:
data = data.drop("Unnamed: 0", axis=1)

In [45]:
data.head(5)

Toxicity                                              tweet
0         0   @user when a father is dysfunctional and is s...
1         0  @user @user thanks for #lyft credit i can't us...
2         0                                bihday your majesty
3         0  #model   i love u take with u all the time in ...
4         0             factsguide: society now    #motivation

In [46]:
data['Toxicity'].value_counts()

Toxicity
0    32592
1    24153
Name: count, dtype: int64

In [47]:
import nltk

# Download necessary NLTK datasets and models
nltk.download('punkt')
nltk.download('omw-1.4')
nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger')

# Import necessary components from NLTK
from nltk import WordNetLemmatizer
from nltk import pos_tag, word_tokenize
from nltk.corpus import stopwords as nltk_stopwords
from nltk.corpus import wordnet


# Example usage
text = "This is an example sentence to demonstrate NLTK usage."
tokens = word_tokenize(text)
pos_tags = pos_tag(tokens)
lemmatizer = WordNetLemmatizer()
stop_words = set(nltk_stopwords.words('english'))

# Output results
print("Tokens:", tokens)
print("POS Tags:", pos_tags)
print("Stop Words:", stop_words)


Tokens: ['This', 'is', 'an', 'example', 'sentence', 'to', 'demonstrate', 'NLTK', 'usage', '.']
POS Tags: [('This', 'DT'), ('is', 'VBZ'), ('an', 'DT'), ('example', 'NN'), ('sentence', 'NN'), ('to', 'TO'), ('demonstrate', 'VB'), ('NLTK', 'NNP'), ('usage', 'NN'), ('.', '.')]
Stop Words: {'out', 'has', 'and', 's', 're', 'y', 'during', 'why', 'ours', 'for', 'was', 'again', 'but', 'each', "you've", 'here', 'very', 'wasn', 'him', 'weren', 'll', 'more', 'once', 'same', 'should', 'have', 'if', 'me', 'them', "mightn't", 'than', 'did', "mustn't", "aren't", "you'll", "you're", 'until', 'will', 'those', 'won', 'am', "it's", 'own', 'theirs', 'yourselves', 'which', 'when', 'through', 'the', 'on', 'been', 'having', 'itself', 'where', 'aren', 'doing', 'at', 'there', "haven't", 'couldn', 't', 'yours', 'a', 'its', 'is', 'off', 'against', "didn't", 'can', "that'll", 'some', 'had', 'wouldn', "couldn't", 'most', 'down', 'ain', 'mustn', 'who', 'does', "should've", 'over', 'how', 'of', 'he', "hadn't", 'don', 

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Manas\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\Manas\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Manas\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Manas\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\Manas\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


## Lemmatizer
1. Leaves
2. Leafs
Leaf

## Text pre-processing

In [48]:
wordnet_lemmatizer = WordNetLemmatizer()

In [49]:
import re

In [50]:
def prepare_text(text):
    def get_wordnet_pos(treebank_tag):
        if treebank_tag.startswith('J'):
            return wordnet.ADJ
        elif treebank_tag.startswith('V'):
            return wordnet.VERB
        elif treebank_tag.startswith('N'):
            return wordnet.NOUN
        elif treebank_tag.startswith('R'):
            return wordnet.ADV
        else:
            return wordnet.NOUN
    text = re.sub(r'[^a-zA-Z\']', ' ', text)
    text = text.split()
    text = ' '.join(text)
    text = word_tokenize(text)
    text = pos_tag(text)
    lemma = []
    for i in text: lemma.append(wordnet_lemmatizer.lemmatize(i[0], pos = get_wordnet_pos(i[1])))
    lemma = ' '.join(lemma)
    return lemma

In [51]:
data['clean_tweets'] = data['tweet'].apply(lambda x: prepare_text(x))

In [52]:
data.head(5)

Toxicity                                              tweet  \
0         0   @user when a father is dysfunctional and is s...   
1         0  @user @user thanks for #lyft credit i can't us...   
2         0                                bihday your majesty   
3         0  #model   i love u take with u all the time in ...   
4         0             factsguide: society now    #motivation   

                                        clean_tweets  
0  user when a father be dysfunctional and be so ...  
1  user user thanks for lyft credit i ca n't use ...  
2                                bihday your majesty  
3      model i love u take with u all the time in ur  
4                  factsguide society now motivation

## Tfidf for features

In [53]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split 
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve

In [54]:
corpus = data['clean_tweets'].values.astype('U')

In [55]:
stopwords = set(nltk_stopwords.words('english'))

In [57]:
from nltk.corpus import stopwords

stop_words = stopwords.words('english')

count_tf_idf = TfidfVectorizer(stop_words=stop_words)
tf_idf = count_tf_idf.fit_transform(corpus)

In [58]:
import pickle

In [59]:
pickle.dump(count_tf_idf, open("tf_idf.pkt", "wb"))

In [60]:
tf_idf_train, tf_idf_test, target_train, target_test = train_test_split(
    tf_idf, data['Toxicity'], test_size = 0.8, random_state= 42, shuffle=True
)

## Create a Binary Classification Model

In [61]:
model_bayes = MultinomialNB()

In [63]:
model_bayes = model_bayes.fit(tf_idf_train, target_train)

In [64]:
y_pred_proba = model_bayes.predict_proba(tf_idf_test)[::, 1]

In [65]:
y_pred_proba

array([0.90152453, 0.27916787, 0.79021827, ..., 0.09487729, 0.20555162,
       0.32090192])

In [66]:
fpr, tpr, _ = roc_curve(target_test, y_pred_proba)

In [67]:
final_roc_auc = roc_auc_score(target_test, y_pred_proba)

In [68]:
final_roc_auc

0.9658691315317345

In [69]:
test_text = "I hate you moron"
test_tfidf = count_tf_idf.transform([test_text])
display(model_bayes.predict_proba(test_tfidf))
display(model_bayes.predict(test_tfidf))

array([[0.39920068, 0.60079932]])

array([1], dtype=int64)

## Save the model

In [70]:
pickle.dump(model_bayes, open("toxicity_model.pkt", "wb"))